
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.demo.ws.zalbepodaci;

import java.util.logging.Logger;

import org.springframework.beans.factory.annotation.Autowired;

import com.example.demo.service.ZalbaService;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-01-03T23:39:24.994+01:00
 * Generated source version: 3.3.0
 *
 */

@javax.jws.WebService(
                      serviceName = "ZalbePodaciService",
                      portName = "ZalbePodaciPort",
                      targetNamespace = "http://demo.example.com/ws/zalbePodaci",
                      wsdlLocation = "classpath:wsdl/ZalbePodaci.wsdl",
                      endpointInterface = "com.example.demo.ws.zalbepodaci.ZalbePodaci")

public class ZalbePodaciPortImpl implements ZalbePodaci {

	@Autowired
	private ZalbaService zalbaService;
	
    private static final Logger LOG = Logger.getLogger(ZalbePodaciPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.example.demo.ws.zalbepodaci.ZalbePodaci#getZalbePodaci(java.math.BigInteger godina)*
     */
    public com.example.demo.ws.zalbepodaci.data.ZalbePodaciData getZalbePodaci(java.math.BigInteger godina) {
        LOG.info("Executing operation getZalbePodaci");
        System.out.println(godina);
        try {
            com.example.demo.ws.zalbepodaci.data.ZalbePodaciData _return = this.zalbaService.retrieveZalbePodaci();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
