package com.example.demo.ws.resenje;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-01-05T19:51:23.722+01:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "CreateResenjeService",
                  wsdlLocation = "classpath:wsdl/Resenje.wsdl",
                  targetNamespace = "http://demo.example.com/ws/resenje")
public class CreateResenjeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://demo.example.com/ws/resenje", "CreateResenjeService");
    public final static QName CreateResenjePort = new QName("http://demo.example.com/ws/resenje", "CreateResenjePort");
    static {
        URL url = CreateResenjeService.class.getClassLoader().getResource("wsdl/Resenje.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(CreateResenjeService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/Resenje.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreateResenjeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreateResenjeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateResenjeService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CreateResenjeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CreateResenjeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CreateResenjeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CreateResenje
     */
    @WebEndpoint(name = "CreateResenjePort")
    public CreateResenje getCreateResenjePort() {
        return super.getPort(CreateResenjePort, CreateResenje.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreateResenje
     */
    @WebEndpoint(name = "CreateResenjePort")
    public CreateResenje getCreateResenjePort(WebServiceFeature... features) {
        return super.getPort(CreateResenjePort, CreateResenje.class, features);
    }

}
