
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.demo.ws.resenje;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-01-05T19:51:23.600+01:00
 * Generated source version: 3.3.0
 *
 */

@javax.jws.WebService(
                      serviceName = "CreateResenjeService",
                      portName = "CreateResenjePort",
                      targetNamespace = "http://demo.example.com/ws/resenje",
                      wsdlLocation = "classpath:wsdl/Resenje.wsdl",
                      endpointInterface = "com.example.demo.ws.resenje.CreateResenje")

public class CreateResenjePortImpl implements CreateResenje {

    private static final Logger LOG = Logger.getLogger(CreateResenjePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.example.demo.ws.resenje.CreateResenje#createResenje(java.lang.String createResenje)*
     */
    public void createResenje(java.lang.String createResenje) {
        LOG.info("Executing operation createResenje");
        System.out.println(createResenje);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
