
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.demo.ws.resenje;

import java.util.logging.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.w3c.dom.Document;

import com.example.demo.parser.DOMParser;
import com.example.demo.repository.ResenjeRepository;

/**
 * This class was generated by Apache CXF 3.3.0 2021-01-05T19:51:23.600+01:00
 * Generated source version: 3.3.0
 *
 */

@javax.jws.WebService(serviceName = "CreateResenjeService", portName = "CreateResenjePort", targetNamespace = "http://demo.example.com/ws/resenje", wsdlLocation = "classpath:wsdl/Resenje.wsdl", endpointInterface = "com.example.demo.ws.resenje.CreateResenje")
@Component
public class CreateResenjePortImpl implements CreateResenje {

	private static final Logger LOG = Logger.getLogger(CreateResenjePortImpl.class.getName());

	@Autowired
	private ResenjeRepository resenjeRepository;

	@Autowired
	private DOMParser domParser;

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.example.demo.ws.resenje.CreateResenje#createResenje(java.lang.String
	 * createResenje)*
	 */
	public void createResenje(java.lang.String createResenje) {
		LOG.info("Executing operation createResenje");
		System.out.println(createResenje);
		try {
			Document resenjeDocument = this.domParser.buildDocument(createResenje);
			this.resenjeRepository.save(resenjeDocument, null);
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
