package com.example.demo.ws.resenje;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-01-05T19:51:23.608+01:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://demo.example.com/ws/resenje", name = "CreateResenje")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CreateResenje {

    @WebMethod
    @Oneway
    public void createResenje(
        @WebParam(partName = "createResenje", name = "createResenje", targetNamespace = "http://demo.example.com/ws/resenje")
        java.lang.String createResenje
    );
}
