package com.example.demo.ws.zalba;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-01-05T18:48:48.274+01:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://demo.example.com/ws/zalba", name = "CreateZalba")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CreateZalba {

    @WebMethod
    @Oneway
    public void createZalba(
        @WebParam(partName = "createZalba", name = "createZalba", targetNamespace = "http://demo.example.com/ws/zalba")
        java.lang.String createZalba
    );
}
