package com.example.demo.ws.zalba;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-01-05T18:48:48.398+01:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "CreateZalbaService",
                  wsdlLocation = "classpath:wsdl/Zalba.wsdl",
                  targetNamespace = "http://demo.example.com/ws/zalba")
public class CreateZalbaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://demo.example.com/ws/zalba", "CreateZalbaService");
    public final static QName CreateZalbaPort = new QName("http://demo.example.com/ws/zalba", "CreateZalbaPort");
    static {
        URL url = CreateZalbaService.class.getClassLoader().getResource("wsdl/Zalba.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(CreateZalbaService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/Zalba.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreateZalbaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreateZalbaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateZalbaService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CreateZalbaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CreateZalbaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CreateZalbaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CreateZalba
     */
    @WebEndpoint(name = "CreateZalbaPort")
    public CreateZalba getCreateZalbaPort() {
        return super.getPort(CreateZalbaPort, CreateZalba.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreateZalba
     */
    @WebEndpoint(name = "CreateZalbaPort")
    public CreateZalba getCreateZalbaPort(WebServiceFeature... features) {
        return super.getPort(CreateZalbaPort, CreateZalba.class, features);
    }

}
