
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.demo.ws.zalba;

import java.util.logging.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.w3c.dom.Document;

import com.example.demo.parser.DOMParser;
import com.example.demo.repository.ZalbaRepository;

/**
 * This class was generated by Apache CXF 3.3.0 2021-01-05T18:48:46.463+01:00
 * Generated source version: 3.3.0
 *
 */

@javax.jws.WebService(serviceName = "CreateZalbaService", portName = "CreateZalbaPort", targetNamespace = "http://demo.example.com/ws/zalba", wsdlLocation = "classpath:wsdl/Zalba.wsdl", endpointInterface = "com.example.demo.ws.zalba.CreateZalba")
@Component
public class CreateZalbaPortImpl implements CreateZalba {

	private static final Logger LOG = Logger.getLogger(CreateZalbaPortImpl.class.getName());

	@Autowired
	private ZalbaRepository zalbaRepository;

	@Autowired
	private DOMParser domParser;

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.example.demo.ws.zalba.CreateZalba#createZalba(java.lang.String
	 * createZalba)*
	 */
	public void createZalba(java.lang.String createZalba) {
		LOG.info("Executing operation createZalba");
		System.out.println(createZalba);
		try {
			Document zalbaDocument = this.domParser.buildDocument(createZalba);
			this.zalbaRepository.save(zalbaDocument, null);
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
