
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.demo.ws.zalba;

import java.util.logging.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import com.example.demo.service.zalba.ZalbaService;

/**
 * This class was generated by Apache CXF 3.3.0 2021-01-05T18:48:46.463+01:00
 * Generated source version: 3.3.0
 *
 */

@javax.jws.WebService(serviceName = "ZalbaService", portName = "ZalbaPort", targetNamespace = "http://demo.example.com/ws/zalba", wsdlLocation = "classpath:wsdl/Zalba.wsdl", endpointInterface = "com.example.demo.ws.zalba.Zalba")
@Component
public class ZalbaPortImpl implements Zalba {

	private static final Logger LOG = Logger.getLogger(ZalbaPortImpl.class.getName());

	@Autowired
	private ZalbaService zalbaService;

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.example.demo.ws.zalba.CreateZalba#createZalba(java.lang.String
	 * createZalba)*
	 */
	public void createZalba(java.lang.String createZalba) {
		LOG.info("Executing operation createZalba");
		System.out.println(createZalba);
		try {
			this.zalbaService.save(createZalba);
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
