package com.example.demo.ws.izvestaj;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-01-09T03:26:14.301+01:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://demo.example.com/ws/izvestaj", name = "Izvestaj")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Izvestaj {

    @WebMethod
    @Oneway
    public void createIzvestaj(
        @WebParam(partName = "createIzvestaj", name = "createIzvestaj", targetNamespace = "http://demo.example.com/ws/izvestaj")
        java.lang.String createIzvestaj
    );
}
