
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.demo.ws.izvestaj;

import java.util.logging.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.example.demo.service.izvestaj.IzvestajService;

/**
 * This class was generated by Apache CXF 3.3.0 2021-01-09T03:26:14.296+01:00
 * Generated source version: 3.3.0
 *
 */

@javax.jws.WebService(serviceName = "IzvestajService", portName = "IzvestajPort", targetNamespace = "http://demo.example.com/ws/izvestaj", wsdlLocation = "classpath:wsdl/Izvestaj.wsdl", endpointInterface = "com.example.demo.ws.izvestaj.Izvestaj")
@Component
public class IzvestajPortImpl implements Izvestaj {

	private static final Logger LOG = Logger.getLogger(IzvestajPortImpl.class.getName());

	@Autowired
	private IzvestajService izvestajService;

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.example.demo.ws.izvestaj.Izvestaj#createIzvestaj(java.lang.String
	 * createIzvestaj)*
	 */
	public void createIzvestaj(java.lang.String createIzvestaj) {
		LOG.info("Executing operation createIzvestaj");
		System.out.println(createIzvestaj);
		try {
			this.izvestajService.save(createIzvestaj);
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
