
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.demo.ws.odgovor;

import java.util.logging.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.example.demo.service.odgovor.OdgovorService;

/**
 * This class was generated by Apache CXF 3.3.0 2021-01-06T14:32:19.333+01:00
 * Generated source version: 3.3.0
 *
 */

@javax.jws.WebService(serviceName = "OdgovorService", portName = "OdgovorPort", targetNamespace = "http://demo.example.com/ws/odgovor", wsdlLocation = "classpath:wsdl/Odgovor.wsdl", endpointInterface = "com.example.demo.ws.odgovor.Odgovor")
@Component
public class OdgovorPortImpl implements Odgovor {

    private static final Logger LOG = Logger.getLogger(OdgovorPortImpl.class.getName());
    
    @Autowired
    private OdgovorService odgovorService;

    /* (non-Javadoc)
     * @see com.example.demo.ws.odgovor.CreateOdgovor#createOdgovor(java.lang.String createOdgovor)*
     */
    public void createOdgovor(java.lang.String createOdgovor) {
        LOG.info("Executing operation createOdgovor");
        System.out.println(createOdgovor);
        try {
            this.odgovorService.save(createOdgovor);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
