package com.example.demo.ws.odluka;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-01-07T22:55:58.538+01:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://demo.example.com/ws/odluka", name = "Odluka")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Odluka {

    @WebMethod
    @WebResult(name = "createOdlukaResponse", targetNamespace = "http://demo.example.com/ws/odluka", partName = "createOdlukaResponse")
    public java.lang.String createOdluka(
        @WebParam(partName = "createOdlukaRequest", name = "createOdlukaRequest", targetNamespace = "http://demo.example.com/ws/odluka")
        java.lang.String createOdlukaRequest
    );
}
