package com.example.demo.ws.zahtev;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-01-07T22:55:55.775+01:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://demo.example.com/ws/zahtev", name = "Zahtev")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Zahtev {

    @WebMethod
    @WebResult(name = "createZahtevResponse", targetNamespace = "http://demo.example.com/ws/zahtev", partName = "createZahtevResponse")
    public java.lang.String createZahtev(
        @WebParam(partName = "createZahtevRequest", name = "createZahtevRequest", targetNamespace = "http://demo.example.com/ws/zahtev")
        java.lang.String createZahtevRequest
    );
}
