
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.demo.ws.zahtev;

import java.util.logging.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.example.demo.service.zahtev.ZahtevService;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-01-07T22:55:53.999+01:00
 * Generated source version: 3.3.0
 *
 */

@javax.jws.WebService(
                      serviceName = "ZahtevService",
                      portName = "ZahtevPort",
                      targetNamespace = "http://demo.example.com/ws/zahtev",
                      wsdlLocation = "classpath:wsdl/Zahtev.wsdl",
                      endpointInterface = "com.example.demo.ws.zahtev.Zahtev")
@Component
public class ZahtevPortImpl implements Zahtev {

    private static final Logger LOG = Logger.getLogger(ZahtevPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.example.demo.ws.zahtev.Zahtev#createZahtev(java.lang.String createZahtevRequest)*
     */
    
    @Autowired
    private ZahtevService zahtevService;
    
    public java.lang.String createZahtev(java.lang.String createZahtevRequest) {
        LOG.info("Executing operation createZahtev");
        System.out.println(createZahtevRequest);
        try {
            java.lang.String _return = this.zahtevService.load(createZahtevRequest);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
